### ISSUE TITLE
animated={true} causing white screen on android.

### ISSUE THREAD

**Issue by umangloria** [rarenatoe/more-or-less#2]
I was having animated property enabled and it is working fine on iOS but when I checked on android, If I move to that screen it remains white and empty.
Strange enough, All the buttons and everything are there but just not visible. I can press any button on that screen as I know where should be that buttons and everything starts showing up fine.
I started looking into what can cause the problem by commenting out components one by one and then if I comment out this component then it starts working normally.
So I tried looking at all properties that I am using with this component and I found that if I remove the animated property it fixes the issue so right now I enabled animated only for iOS.

**Comment by rarenatoe** [comment]
Thanks for reporting it. That's pretty weird. I'll take a look over this weekend.

**Comment by rarenatoe** [comment]
@umangloria could you tell me what version of Android are you using?

**Comment by rarenatoe** [comment]
I have tried resolving this issue, but I am not encountering the error, so I might need more information.
For now I'm closing it.

**Comment by kokosky93** [comment]
Hi, I have the same problem on android. Animated option set to true causes black screen

`
<MoreOrLess
                    key={refreshIndicator}
                    numberOfLines={8}
                    textStyle={{ color: '#878a91', fontSize: 18 }}
                    textButtonStyle={{ color: 'white', backgroundColor: 'black', fontWeight: '400', fontSize: 18 }}
                    animated={false}
                    moreText="more"
                    lessText="less"
                >
                    {dto.description}
                </MoreOrLess>
`

**Comment by rarenatoe** [comment]
@kokosky93 I tested again, I'm again not finding the issue. If possible please share you Android OS version, and react native version.
