### ISSUE TITLE
Dynamically changing the children doesn't change what is shown in the less

### ISSUE THREAD

**Issue by alecgorge** [rarenatoe/more-or-less#6]
`lines` is not updated when the `children` change so when you swap out the text, the full text isn't laid out again so it keeps the old text. When you press "more" it expands to the correct, new text.

It isn't clear to me how to easily invalidate a whole bunch of these on a screen at once. If I come up with a solution/patch I will post back here.

Also, thanks for the cool & efficient component!

**Comment by rarenatoe** [comment]
Thanks for letting me know! I'll check this out soon!

**Comment by justynpollard1** [comment]
Any update? I am also running into this issue

**Comment by justynpollard1** [comment]
After looking at the code, its not really possible to fix this without some core changes, but if anyone runs into this probably a quick but not ideal fix is just to make the children string the key, so it rerenders it when changing the children.
`<MoreOrLess
          key={product.description}
          numberOfLines={2}
          textButtonStyle={styles.readMore}
          textStyle={styles.descriptionText}
          moreText={"Read more"}
          lessText={"Read less"}
        >
          {product.description}
        </MoreOrLess>`
